"""Initial migration

Revision ID: 9ff68cec15aa
Revises: 
Create Date: 2024-08-13 17:28:54.385465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff68cec15aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parents',
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('surname', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tutors',
    sa.Column('second_name', sa.String(length=32), nullable=False),
    sa.Column('lesson_max_duration', sa.Integer(), nullable=False),
    sa.Column('discord', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('surname', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('lessontypes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tutor', sa.BigInteger(), nullable=False),
    sa.Column('lesson_subtype', sa.Enum('individual', 'group', name='lessontypesenum'), nullable=True),
    sa.ForeignKeyConstraint(['tutor'], ['tutors.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('students',
    sa.Column('parent', sa.BigInteger(), nullable=True),
    sa.Column('discord', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('surname', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent'], ['parents.user_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_type', sa.Integer(), nullable=False),
    sa.Column('student', sa.BigInteger(), nullable=False),
    sa.Column('tutor', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('day_of_week', sa.Enum('in_process', 'reviewing', 'declined', 'accepted', name='paymentstatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_type'], ['lessontypes.id'], ),
    sa.ForeignKeyConstraint(['student'], ['students.user_id'], ),
    sa.ForeignKeyConstraint(['tutor'], ['tutors.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('regularlessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_type', sa.Integer(), nullable=False),
    sa.Column('student', sa.BigInteger(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='dayofweekenum'), nullable=True),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_type'], ['lessontypes.id'], ),
    sa.ForeignKeyConstraint(['student'], ['students.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('singlelessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_type', sa.Integer(), nullable=False),
    sa.Column('student', sa.BigInteger(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('is_payed', sa.Integer(), nullable=True),
    sa.Column('lesson_status', sa.Enum('scheduled', 'completed', 'cancelled', name='lessonstatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_type'], ['lessontypes.id'], ),
    sa.ForeignKeyConstraint(['student'], ['students.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('singleregularlessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('regular_lesson', sa.Integer(), nullable=False),
    sa.Column('lesson_status', sa.Enum('scheduled', 'completed', 'cancelled', name='lessonstatusenum'), nullable=True),
    sa.Column('is_payed', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['regular_lesson'], ['regularlessons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('singleregularlessons')
    op.drop_table('singlelessons')
    op.drop_table('regularlessons')
    op.drop_table('payments')
    op.drop_table('students')
    op.drop_table('lessontypes')
    op.drop_table('tutors')
    op.drop_table('parents')
    # ### end Alembic commands ###
