"""Add balance column to student and parent

Revision ID: aa76937d9178
Revises: 203a61abb465
Create Date: 2024-09-04 00:22:03.500215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa76937d9178'
down_revision: Union[str, None] = '203a61abb465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents', sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('students', sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'balance')
    op.drop_column('parents', 'balance')
    # ### end Alembic commands ###
